language: node_js
node_js:
    - '12'
branches:
  only:
    - master
install:
    - npm install
script:
    - npm run build
after_script:
  - ls -a
  - git init
  - git config user.name ${GH_USER}
  - git config user.email ${GH_EMAIL}
  - git add .
  - git commit -m "commit 222"
  - git status
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:dev
